import dev.schlaubi.lejos.gradle.LejosRunTask

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5.1/samples
 */

plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(files(lejosHome("lib", "ev3", "ev3classes.jar")))
}

tasks {
    task<LejosRunTask>("runTest1") {
        mainClass("Test")
    }
}
